#!/bin/bash

#############################################
#
#	TBSS 2 
#	Created by Corinne McGill
#	Modified by Kayti Keith
#	11/16/20
#      
#############################################


#Pathways
export input=/Path/to/study/Phase1/DKI/fa
export ID_file=/Path/to/study/Scripts/IDs.txt

cd $input
tbss_2_reg -T

gunzip $input/FA/*nii.gz