#!/bin/bash

#############################################
#
#	TBSS 3 
#	Created by Corinne McGill
#	Modified by Kayti Keith
#	11/16/20
#      
#############################################


#Pathways
export input=/Path/to/study/Phase1/DKI/fa

cd $input
tbss_3_postreg -T

gunzip $input/FA/*nii.gz