#!/bin/bash

#############################################
#
#	TBSS 4 Prestats DKI
#	Created by Corinne McGill
#	Modified by Kayti Keith
#	11/16/20
#      
#############################################


#Pathways
export input=/Path/to/study/Phase1/DKI/fa

cd $input
tbss_4_prestats 0.2
echo tbss_4 complete

cd $input/FA
gunzip *nii.gz

cd $input/stats
gunzip *nii.gz