#!/bin/bash

#############################################
#
#	TBSS 1 
#	Created by Corinne McGill
#	Modified by Kayti Keith
#	7/27/20
#      
#############################################


export input=/path-to-project/Phase1/DKI/fa

cd $input
tbss_1_preproc *.nii
