#!/bin/bash

#############################################
#
#	TBSS 4 Prestats WMM
#	Created by Corinne McGill
#	Modified by Kayti Keith
#	7/27/20
#      
#############################################


export input=/path-to-project/Phase1/DKI/fa
export output=/path-to-project/Phase1/WMM/fa

cp -R $input $output

cd $output
tbss_4_prestats 0.4

cd $output/stats
gunzip *nii.gz